apiVersion: v1
kind: Service
metadata:
  name: physics-admission-controller
  namespace: physics-infra
  labels:
    app: physics-admission-controller
spec:
  ports:
  - port: 443
    targetPort: 6443
  selector:
    app: physics-admission-controller
